language: java
jdk: oraclejdk8

before_install:
- "sed -i \"s/^\\(version:.*\\)/\\1.$TRAVIS_BUILD_NUMBER/\" src/main/resources/plugin.yml"
- pushd ~/build/
- git clone --depth=1 https://github.com/NyaaCat/NyaaCore NyaaCat/NyaaCore
- export NYAACORE_LANG_DIR=`readlink -f ./NyaaCat/NyaaCore/src/main/resources/lang/`
- popd
after_success:
- 'cp build/libs/RPGitems-reloaded.jar ./rpgitem-reloaded-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar'

before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v3.6.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GITHUB_KEY@github.com/NyaaCat/RPGitems-reloaded --follow-tags

deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true
  api_key: $GITHUB_KEY
  file: './rpgitem-reloaded-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar'
  on:
    tags: false
    all_branches: true

branches:
  except:
  - "/^*-v[0-9]/"