language: java
jdk: oraclejdk8

before_install:
- export MAJOR_VERSION=`sed -n 's/^ext\.majorVersion = \(.*\)$/\1/p' build.gradle`
- export MINOR_VERSION=`sed -n 's/^ext\.minorVersion = \(.*\)$/\1/p' build.gradle`
- export MC_VERSION=`sed -n 's/^ext\.minecraftVersion = "\(.*\)"$/\1/p' build.gradle`
- export VERSION_STRING=$MAJOR_VERSION.$MINOR_VERSION.$TRAVIS_BUILD_NUMBER-mc$MC_VERSION
- 'sed -i "s/^\(version: \).*\$/\1$VERSION_STRING/g" src/main/resources/plugin.yml'
- pushd ~/build/
- git clone --depth=1 https://github.com/NyaaCat/NyaaCore NyaaCat/NyaaCore
- export NYAACORE_LANG_DIR=`readlink -f ./NyaaCat/NyaaCore/src/main/resources/lang/`
- popd
after_success:
- 'cp build/libs/RPGitems-reloaded.jar ./rpgitem-reloaded-$VERSION_STRING.jar'

before_deploy:
- if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[unstable]" ; then echo "skipping travis deploy" && exit 0 ; fi
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_KEY}:@github.com" > .git/credentials
- git push -q origin HEAD:$TRAVIS_BRANCH --follow-tags

deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true
  api_key: $GITHUB_KEY
  file: './rpgitem-reloaded-$VERSION_STRING.jar'
  body: 'RPGitems build $TRAVIS_BUILD_NUMBER for spigot $TRAVIS_BRANCH'
  on:
    tags: false
    all_branches: true

branches:
  except:
  - "/^*-v[0-9]/"