name: RPGItems
main: think.rpgitems.RPGItems
description: "RPGItems"
version: 3.7.686986-mc1.13.2
depend: [NyaaCore,LangUtils]
softdepend: [WorldGuard,NyaaUtils]
authors: [Taiterio,cyilin,RecursiveG,Librazy]
website: "https://github.com/NyaaCat/RPGItems-reloaded"
database: false
api-version: 1.13

commands:
  rpgitem:
    description: RPG Items
    permission: rpgitem
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  rpgitem.allowenchant.new:
    default: op
  rpgitem.allowenchant.old:
    default: op
  rpgitem.updateitem:
    default: op